CREATE TABLE chuangxin.token (
  access_token VARCHAR(255),
  token_type VARCHAR(255),
  refresh_token VARCHAR(255),
  expires_in INT,
  scope VARCHAR(255),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE chuangxin.task (
  task_type VARCHAR(255),
  max_pd VARCHAR(255),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
