SET 'execution.runtime-mode' = 'batch';
SET 'sql-client.execution.result-mode' = 'tableau';
SET 'sql-client.execution.max-table-result.rows' = '10000';
SET 'parallelism.default' = '1';
SET 'table.optimizer.join-reorder-enabled' = 'true';
SET 'table.exec.spill-compression.enabled' = 'true';
SET 'table.exec.spill-compression.block-size' = '128kb';
SET 'pipeline.name' = 'FLINK-ODS:PATENT_SEARCH_EXPRESSION';

CREATE TABLE patent_search_expression (
_id STRING,
pid STRING COMMENT '专利编码',
pno STRING COMMENT '文献号-原始',
tic STRING COMMENT '标题-中文',
tie STRING COMMENT '标题-英文',
tio STRING COMMENT '标题-原始',
ano STRING COMMENT '申请号-原始',
ad STRING COMMENT '申请日',
pd STRING COMMENT '公开日',
pk STRING COMMENT '文献类型',
apo STRING COMMENT '申请人-原始',
ape STRING COMMENT '申请人-英文',
apc STRING COMMENT '申请人-中文',
ipc STRING COMMENT 'IPC',
lc STRING COMMENT '洛迦诺分类',
vu STRING COMMENT '专利强度',
abso STRING COMMENT '摘要-原始语种',
abse STRING COMMENT '摘要-英文',
absc STRING COMMENT '摘要-中文',
IMGTITLE STRING COMMENT '缩略图',
IMGNAME STRING COMMENT '缩略图名称',
lssc STRING COMMENT '当前权利状态',
lsscn STRING COMMENT '当前权利状态中文',
pdt STRING COMMENT '专利类型',
debec STRING COMMENT '简要说明-中文',
debeo STRING COMMENT '简要说明-原始',
debee STRING COMMENT '简要说明-英文',
IMGO STRING COMMENT '原始图',
pdfexist STRING COMMENT '是否存在PDF',
ans STRING COMMENT '申请号标准',
pns STRING COMMENT '公布号标准',
sfpns STRING COMMENT '代表性文献号',
imglisttitle STRING COMMENT '缩略图列表',
imglistname STRING COMMENT '缩略图名称列表',
inc STRING COMMENT '发明人-中文',
ine STRING COMMENT '发明人-英文',
ino STRING COMMENT '发明人-原文',
agc STRING COMMENT '代理人-中文',
age STRING COMMENT '代理人-英文',
ago STRING COMMENT '代理人-原文',
`asc` STRING COMMENT '专利权人-中文',
ase STRING COMMENT '专利权人-英文',
aso STRING COMMENT '专利权人-原文',
exc STRING COMMENT '审查员-中文',
exe STRING COMMENT '审查员人-英文',
exo STRING COMMENT '审查员-原文',
crc STRING COMMENT '代理机构中文',
cre STRING COMMENT '代理机构英文',
cro STRING COMMENT '代理机构原始',
cri STRING COMMENT '代理机构代码',
tcc STRING COMMENT '转让次数',
pcc STRING COMMENT '许可次数',
ppc STRING COMMENT '质押次数',
pinc STRING COMMENT '无效次数',
plic STRING COMMENT '诉讼次数',
depc STRING COMMENT '说明书页数',
pct STRING COMMENT 'PCT',
ap1ado STRING COMMENT '申请人地址',
apac STRING COMMENT '申请人区域代码',
as1ado STRING COMMENT '专利权人地址',
rd STRING COMMENT '失效日期',
aspo STRING COMMENT '当前权利人原始',
asp1ado STRING COMMENT '当前权利人地址',
aspac STRING COMMENT '当前权利人区域代码',
cln STRING COMMENT '权利要求数量',
lsbcn STRING COMMENT '法律状态二级',
highpat STRING COMMENT '高价值专利',
citnto STRING COMMENT '新兴产业名称',
awgdo STRING COMMENT '奖励级别原文',
awto STRING COMMENT '奖励名称原文',
awyo STRING COMMENT '奖励届次原文',
  PRIMARY KEY (_id) NOT ENFORCED
)with(
   'connector' = 'mongodb',
   'uri' = 'mongodb://fastsay.cn:27017',
   'database' = 'sync',
   'collection' = 'patent_search_expression'
 );


--读
CREATE TABLE ods_patent_search_expression (
pid STRING COMMENT '专利编码',
pno STRING COMMENT '文献号-原始',
tic STRING COMMENT '标题-中文',
tie STRING COMMENT '标题-英文',
tio STRING COMMENT '标题-原始',
ano STRING COMMENT '申请号-原始',
ad STRING COMMENT '申请日',
pd STRING COMMENT '公开日',
pk STRING COMMENT '文献类型',
apo STRING COMMENT '申请人-原始',
ape STRING COMMENT '申请人-英文',
apc STRING COMMENT '申请人-中文',
ipc STRING COMMENT 'IPC',
lc STRING COMMENT '洛迦诺分类',
vu STRING COMMENT '专利强度',
abso STRING COMMENT '摘要-原始语种',
abse STRING COMMENT '摘要-英文',
absc STRING COMMENT '摘要-中文',
IMGTITLE STRING COMMENT '缩略图',
IMGNAME STRING COMMENT '缩略图名称',
lssc STRING COMMENT '当前权利状态',
lsscn STRING COMMENT '当前权利状态中文',
pdt STRING COMMENT '专利类型',
debec STRING COMMENT '简要说明-中文',
debeo STRING COMMENT '简要说明-原始',
debee STRING COMMENT '简要说明-英文',
IMGO STRING COMMENT '原始图',
pdfexist STRING COMMENT '是否存在PDF',
ans STRING COMMENT '申请号标准',
pns STRING COMMENT '公布号标准',
sfpns STRING COMMENT '代表性文献号',
imglisttitle STRING COMMENT '缩略图列表',
imglistname STRING COMMENT '缩略图名称列表',
inc STRING COMMENT '发明人-中文',
ine STRING COMMENT '发明人-英文',
ino STRING COMMENT '发明人-原文',
agc STRING COMMENT '代理人-中文',
age STRING COMMENT '代理人-英文',
ago STRING COMMENT '代理人-原文',
`asc` STRING COMMENT '专利权人-中文',
ase STRING COMMENT '专利权人-英文',
aso STRING COMMENT '专利权人-原文',
exc STRING COMMENT '审查员-中文',
exe STRING COMMENT '审查员人-英文',
exo STRING COMMENT '审查员-原文',
crc STRING COMMENT '代理机构中文',
cre STRING COMMENT '代理机构英文',
cro STRING COMMENT '代理机构原始',
cri STRING COMMENT '代理机构代码',
tcc STRING COMMENT '转让次数',
pcc STRING COMMENT '许可次数',
ppc STRING COMMENT '质押次数',
pinc STRING COMMENT '无效次数',
plic STRING COMMENT '诉讼次数',
depc STRING COMMENT '说明书页数',
pct STRING COMMENT 'PCT',
ap1ado STRING COMMENT '申请人地址',
apac STRING COMMENT '申请人区域代码',
as1ado STRING COMMENT '专利权人地址',
rd STRING COMMENT '失效日期',
aspo STRING COMMENT '当前权利人原始',
asp1ado STRING COMMENT '当前权利人地址',
aspac STRING COMMENT '当前权利人区域代码',
cln STRING COMMENT '权利要求数量',
lsbcn STRING COMMENT '法律状态二级',
highpat STRING COMMENT '高价值专利',
citnto STRING COMMENT '新兴产业名称',
awgdo STRING COMMENT '奖励级别原文',
awto STRING COMMENT '奖励名称原文',
awyo STRING COMMENT '奖励届次原文',
PRIMARY KEY (pid) NOT ENFORCED
)with(
   'connector'='starrocks',
   'scan-url'='bigdata01:8030,bigdata02:8030,bigdata03:8030',
   'jdbc-url'='jdbc:mysql://bigdata01:9030',
   'username'='root',
   'password'='',
   'database-name'='ods',
   'table-name'='ods_patent_search_expression'
);

--写

CREATE TABLE ods_patent_search_expression (
pid STRING COMMENT '专利编码',
pno STRING COMMENT '文献号-原始',
tic STRING COMMENT '标题-中文',
tie STRING COMMENT '标题-英文',
tio STRING COMMENT '标题-原始',
ano STRING COMMENT '申请号-原始',
ad STRING COMMENT '申请日',
pd STRING COMMENT '公开日',
pk STRING COMMENT '文献类型',
apo STRING COMMENT '申请人-原始',
ape STRING COMMENT '申请人-英文',
apc STRING COMMENT '申请人-中文',
ipc STRING COMMENT 'IPC',
lc STRING COMMENT '洛迦诺分类',
vu STRING COMMENT '专利强度',
abso STRING COMMENT '摘要-原始语种',
abse STRING COMMENT '摘要-英文',
absc STRING COMMENT '摘要-中文',
IMGTITLE STRING COMMENT '缩略图',
IMGNAME STRING COMMENT '缩略图名称',
lssc STRING COMMENT '当前权利状态',
lsscn STRING COMMENT '当前权利状态中文',
pdt STRING COMMENT '专利类型',
debec STRING COMMENT '简要说明-中文',
debeo STRING COMMENT '简要说明-原始',
debee STRING COMMENT '简要说明-英文',
IMGO STRING COMMENT '原始图',
pdfexist STRING COMMENT '是否存在PDF',
ans STRING COMMENT '申请号标准',
pns STRING COMMENT '公布号标准',
sfpns STRING COMMENT '代表性文献号',
imglisttitle STRING COMMENT '缩略图列表',
imglistname STRING COMMENT '缩略图名称列表',
inc STRING COMMENT '发明人-中文',
ine STRING COMMENT '发明人-英文',
ino STRING COMMENT '发明人-原文',
agc STRING COMMENT '代理人-中文',
age STRING COMMENT '代理人-英文',
ago STRING COMMENT '代理人-原文',
`asc` STRING COMMENT '专利权人-中文',
ase STRING COMMENT '专利权人-英文',
aso STRING COMMENT '专利权人-原文',
exc STRING COMMENT '审查员-中文',
exe STRING COMMENT '审查员人-英文',
exo STRING COMMENT '审查员-原文',
crc STRING COMMENT '代理机构中文',
cre STRING COMMENT '代理机构英文',
cro STRING COMMENT '代理机构原始',
cri STRING COMMENT '代理机构代码',
tcc STRING COMMENT '转让次数',
pcc STRING COMMENT '许可次数',
ppc STRING COMMENT '质押次数',
pinc STRING COMMENT '无效次数',
plic STRING COMMENT '诉讼次数',
depc STRING COMMENT '说明书页数',
pct STRING COMMENT 'PCT',
ap1ado STRING COMMENT '申请人地址',
apac STRING COMMENT '申请人区域代码',
as1ado STRING COMMENT '专利权人地址',
rd STRING COMMENT '失效日期',
aspo STRING COMMENT '当前权利人原始',
asp1ado STRING COMMENT '当前权利人地址',
aspac STRING COMMENT '当前权利人区域代码',
cln STRING COMMENT '权利要求数量',
lsbcn STRING COMMENT '法律状态二级',
highpat STRING COMMENT '高价值专利',
citnto STRING COMMENT '新兴产业名称',
awgdo STRING COMMENT '奖励级别原文',
awto STRING COMMENT '奖励名称原文',
awyo STRING COMMENT '奖励届次原文',
PRIMARY KEY (pid,pno) NOT ENFORCED
)with(
'connector' = 'starrocks',
'jdbc-url'='jdbc:mysql://bigdata01:9030,bigdata02:9030,bigdata03:9030',
'load-url'='bigdata01:8030;bigdata01:8030;bigdata01:8030',
'database-name' = 'ods',
'table-name' = 'ods_patent_search_expression',
'username' = 'root',
'password' = '',
'sink.buffer-flush.max-rows' = '1000000',
'sink.buffer-flush.max-bytes' = '300000000',
'sink.buffer-flush.interval-ms' = '5000',
'sink.properties.column_separator' = '\\x01',
'sink.properties.row_delimiter' = '\\x02',
'sink.max-retries' = '3',
'sink.parallelism' = '1'
);


INSERT INTO ods_patent_search_expression
SELECT pid ,
       pno ,
       tic ,
       tie ,
       tio ,
       ano ,
       ad ,
       pd ,
       pk ,
       apo ,
       ape ,
       apc ,
       ipc ,
       lc ,
       vu ,
       abso ,
       abse ,
       absc ,
       IMGTITLE ,
       IMGNAME ,
       lssc ,
       lsscn ,
       pdt ,
       debec ,
       debeo ,
       debee ,
       IMGO ,
       pdfexist ,
       ans ,
       pns ,
       sfpns ,
       imglisttitle ,
       imglistname ,
       inc ,
       ine ,
       ino ,
       agc ,
       age ,
       ago ,
       asc ,
       ase ,
       aso ,
       exc ,
       exe ,
       exo ,
       crc ,
       cre ,
       cro ,
       cri ,
       tcc ,
       pcc ,
       ppc ,
       pinc ,
       plic ,
       depc ,
       pct ,
       ap1ado ,
       apac ,
       as1ado ,
       rd ,
       aspo ,
       asp1ado ,
       aspac ,
       cln ,
       lsbcn ,
       highpat ,
       citnto ,
       awgdo ,
       awto ,
       awyo FROM patent_search_expression;